name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Git Status Output
      run: git status
    - name: Git Commit Ouput
      run: git rev-parse HEAD
    - name: Git OriginURL Output
      run: git config --local --get remote.origin.url
    - name: Build
      id: Build
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      run: dotnet pack ./BeatSaberModdingTools.Tasks/BeatSaberModdingTools.Tasks.csproj -c Release -o ./artifacts --no-restore --include-symbols
    - name: Test
      run: dotnet test --no-restore --verbosity normal --logger GitHubActions
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.Build.outputs.filename }}
        path: ./artifacts
